Remove husky as a dependency as we don't use that anymore
teamleadercrm/ui pull request #1488
Opened 2021-02-11 09:59 UTC by sanderbrugge

### Description

- Removed the `husky` dependency as we don't use this anymore. see #1487

2021-02-11 10:01 UTC, driesd approved these changes

2021-02-11 10:12 UTC, lorgan3 approved these changes

2021-02-11 10:22 UTC, ArnaudWeyts requested changes
🤔 We do use it though, there's a `.huskyrc` file in the root directory

2021-02-16 10:53 UTC, driesd commented
@ArnaudWeyts 's got a point here... ☝️  Closing this PR.

2021-02-16 10:53 UTC, closed without merging