[FRAF-552] Add onClick event handler to the Widget Header
teamleadercrm/ui pull request #2089
Opened 2022-04-15 09:28 UTC by farazatarodi

### Description

Adds onClick event handler to the Widget Header.

2022-04-15 11:02 UTC, ArnaudWeyts submitted a review, later dismissed

2022-04-15 12:39 UTC, jelledc requested changes
I believe you still need to update the changelog :slightly_smiling_face:

2022-04-15 14:17 UTC, jelledc approved these changes

2022-04-19 06:58 UTC, qubis741 approved these changes

2022-04-19 07:07 UTC, qubis741 commented
Q: Shouldn't there be `cursor: pointer` style when header is clickable? Also some story with `onClick` would be useful. Otherwise MCed, works.

2022-04-19 07:31 UTC, driesd approved these changes

2022-04-19 07:33 UTC, merged