[TIDAL-2039] Email selector menu can be the same width as input
teamleadercrm/ui pull request #2205
Opened 2022-06-14 11:32 UTC by BeirlaenAaron

### Description

[Jira](https://teamleader.atlassian.net/browse/TIDAL-2039)

This PR allows the autocomplete menu of the email selector to take the same width as it's input
(Also makes the space between the input and the menu a little bit smaller as requested in the ticket)

#### Screenshot before this PR

![image](https://user-images.githubusercontent.com/55881661/173566686-649f8c42-10f9-4057-9787-fb9af39e9cb9.png)

#### Screenshot after this PR

If the `menuFullWidth` prop is on the email selector, it should look like this:
![image](https://user-images.githubusercontent.com/55881661/173566117-6fb2ef1e-f8db-4b13-b8c4-e18e9c15f731.png)

### Breaking changes

N/A
It's set as an optional prop to avoid breaking changes

2022-06-14 14:12 UTC, stefaandevylder requested changes
This needs to be added to the changelog

2022-06-14 14:46 UTC, driesd approved these changes

2022-06-14 14:47 UTC, lowiebenoot commented on CHANGELOG.md
> +### Fixed=======
I think you did a little oopsie here.

2022-06-14 14:48 UTC, lowiebenoot commented
In which case would it not look good? I would also opt for always giving it the full width, just like our Select component does.

2022-06-14 14:53 UTC, BeirlaenAaron commented on CHANGELOG.md
> +### Fixed=======
That is indeed an oopsie 😅

2022-06-15 08:22 UTC, qubis741 approved these changes

2022-06-16 06:22 UTC, lorgan3 approved these changes

2022-06-16 07:30 UTC, jelledc approved these changes

2022-06-16 15:08 UTC, lowiebenoot approved these changes

2022-06-17 07:11 UTC, stefaandevylder commented
MC'ing so UI can be deployed

2022-06-17 07:16 UTC, merged